// Generated by gencpp from file nav_stack_files/Initial_poseResponse.msg
// DO NOT EDIT!


#ifndef NAV_STACK_FILES_MESSAGE_INITIAL_POSERESPONSE_H
#define NAV_STACK_FILES_MESSAGE_INITIAL_POSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace nav_stack_files
{
template <class ContainerAllocator>
struct Initial_poseResponse_
{
  typedef Initial_poseResponse_<ContainerAllocator> Type;

  Initial_poseResponse_()
    : this_pose()  {
    }
  Initial_poseResponse_(const ContainerAllocator& _alloc)
    : this_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _this_pose_type;
  _this_pose_type this_pose;





  typedef boost::shared_ptr< ::nav_stack_files::Initial_poseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nav_stack_files::Initial_poseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Initial_poseResponse_

typedef ::nav_stack_files::Initial_poseResponse_<std::allocator<void> > Initial_poseResponse;

typedef boost::shared_ptr< ::nav_stack_files::Initial_poseResponse > Initial_poseResponsePtr;
typedef boost::shared_ptr< ::nav_stack_files::Initial_poseResponse const> Initial_poseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nav_stack_files::Initial_poseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nav_stack_files::Initial_poseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nav_stack_files

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nav_stack_files::Initial_poseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nav_stack_files::Initial_poseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nav_stack_files::Initial_poseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nav_stack_files::Initial_poseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nav_stack_files::Initial_poseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nav_stack_files::Initial_poseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nav_stack_files::Initial_poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "870c0b4171545dbbae81254a8d229368";
  }

  static const char* value(const ::nav_stack_files::Initial_poseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x870c0b4171545dbbULL;
  static const uint64_t static_value2 = 0xae81254a8d229368ULL;
};

template<class ContainerAllocator>
struct DataType< ::nav_stack_files::Initial_poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nav_stack_files/Initial_poseResponse";
  }

  static const char* value(const ::nav_stack_files::Initial_poseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nav_stack_files::Initial_poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose this_pose\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::nav_stack_files::Initial_poseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nav_stack_files::Initial_poseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.this_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Initial_poseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nav_stack_files::Initial_poseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nav_stack_files::Initial_poseResponse_<ContainerAllocator>& v)
  {
    s << indent << "this_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.this_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAV_STACK_FILES_MESSAGE_INITIAL_POSERESPONSE_H
