// Generated by gencpp from file nav_stack_files/Initial_poseRequest.msg
// DO NOT EDIT!


#ifndef NAV_STACK_FILES_MESSAGE_INITIAL_POSEREQUEST_H
#define NAV_STACK_FILES_MESSAGE_INITIAL_POSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nav_stack_files
{
template <class ContainerAllocator>
struct Initial_poseRequest_
{
  typedef Initial_poseRequest_<ContainerAllocator> Type;

  Initial_poseRequest_()
    : give_pose(false)  {
    }
  Initial_poseRequest_(const ContainerAllocator& _alloc)
    : give_pose(false)  {
  (void)_alloc;
    }



   typedef uint8_t _give_pose_type;
  _give_pose_type give_pose;





  typedef boost::shared_ptr< ::nav_stack_files::Initial_poseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nav_stack_files::Initial_poseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Initial_poseRequest_

typedef ::nav_stack_files::Initial_poseRequest_<std::allocator<void> > Initial_poseRequest;

typedef boost::shared_ptr< ::nav_stack_files::Initial_poseRequest > Initial_poseRequestPtr;
typedef boost::shared_ptr< ::nav_stack_files::Initial_poseRequest const> Initial_poseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nav_stack_files::Initial_poseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nav_stack_files::Initial_poseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nav_stack_files

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nav_stack_files::Initial_poseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nav_stack_files::Initial_poseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nav_stack_files::Initial_poseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nav_stack_files::Initial_poseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nav_stack_files::Initial_poseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nav_stack_files::Initial_poseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nav_stack_files::Initial_poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3901075996d9d1def52134e9591165fd";
  }

  static const char* value(const ::nav_stack_files::Initial_poseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3901075996d9d1deULL;
  static const uint64_t static_value2 = 0xf52134e9591165fdULL;
};

template<class ContainerAllocator>
struct DataType< ::nav_stack_files::Initial_poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nav_stack_files/Initial_poseRequest";
  }

  static const char* value(const ::nav_stack_files::Initial_poseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nav_stack_files::Initial_poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool give_pose\n\
";
  }

  static const char* value(const ::nav_stack_files::Initial_poseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nav_stack_files::Initial_poseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.give_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Initial_poseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nav_stack_files::Initial_poseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nav_stack_files::Initial_poseRequest_<ContainerAllocator>& v)
  {
    s << indent << "give_pose: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.give_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAV_STACK_FILES_MESSAGE_INITIAL_POSEREQUEST_H
