// Generated by gencpp from file nav_stack_files/Initial_pose.msg
// DO NOT EDIT!


#ifndef NAV_STACK_FILES_MESSAGE_INITIAL_POSE_H
#define NAV_STACK_FILES_MESSAGE_INITIAL_POSE_H

#include <ros/service_traits.h>


#include <nav_stack_files/Initial_poseRequest.h>
#include <nav_stack_files/Initial_poseResponse.h>


namespace nav_stack_files
{

struct Initial_pose
{

typedef Initial_poseRequest Request;
typedef Initial_poseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Initial_pose
} // namespace nav_stack_files


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nav_stack_files::Initial_pose > {
  static const char* value()
  {
    return "b406c1ab8e345a7a46ea98c82c4055d8";
  }

  static const char* value(const ::nav_stack_files::Initial_pose&) { return value(); }
};

template<>
struct DataType< ::nav_stack_files::Initial_pose > {
  static const char* value()
  {
    return "nav_stack_files/Initial_pose";
  }

  static const char* value(const ::nav_stack_files::Initial_pose&) { return value(); }
};


// service_traits::MD5Sum< ::nav_stack_files::Initial_poseRequest> should match 
// service_traits::MD5Sum< ::nav_stack_files::Initial_pose > 
template<>
struct MD5Sum< ::nav_stack_files::Initial_poseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nav_stack_files::Initial_pose >::value();
  }
  static const char* value(const ::nav_stack_files::Initial_poseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nav_stack_files::Initial_poseRequest> should match 
// service_traits::DataType< ::nav_stack_files::Initial_pose > 
template<>
struct DataType< ::nav_stack_files::Initial_poseRequest>
{
  static const char* value()
  {
    return DataType< ::nav_stack_files::Initial_pose >::value();
  }
  static const char* value(const ::nav_stack_files::Initial_poseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nav_stack_files::Initial_poseResponse> should match 
// service_traits::MD5Sum< ::nav_stack_files::Initial_pose > 
template<>
struct MD5Sum< ::nav_stack_files::Initial_poseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nav_stack_files::Initial_pose >::value();
  }
  static const char* value(const ::nav_stack_files::Initial_poseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nav_stack_files::Initial_poseResponse> should match 
// service_traits::DataType< ::nav_stack_files::Initial_pose > 
template<>
struct DataType< ::nav_stack_files::Initial_poseResponse>
{
  static const char* value()
  {
    return DataType< ::nav_stack_files::Initial_pose >::value();
  }
  static const char* value(const ::nav_stack_files::Initial_poseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAV_STACK_FILES_MESSAGE_INITIAL_POSE_H
